### ISSUE TITLE
Assignment 4 is ready

### ISSUE THREAD

**Issue by arielxhbi** [SES-5215-F2020/xiaohebi-quant#4]
Assignment 4 is ready for grading. Thank you so much!

**Comment by saratepfer** [comment]
Nice job, Ariel! It would be great if you could expand your interpretation of your coefficients to be a bit more specific for each variable/coefficient. For example, how much more do english speakers earn than non-english speakers? How do you know? What is the coefficient? What is the significance of this coefficient? We are hoping to see interpretations of the significance and magnitude of each of the coefficients in your model. Also, currently, your interpretation does not comment on the effect of age.
