### ISSUE TITLE
assignment 5

### ISSUE THREAD

**Issue by arielxhbi** [SES-5215-F2020/xiaohebi-quant#5]
Assignment 5 is ready for grading. Thank you so much!

**Comment by saratepfer** [comment]
nice job, Ariel! One of the main things we were looking for in this assignment was to see which of the models you ran was the preferred model and why. It looks like you did more detailed analysis on model 2, so I am assuming that is your preferred model, but why? It would be great if you could explicitly state the rationale for selecting that model.

Also, in your interpretations of the graphs at the end of your assignment, I think it is important to explicitly state that these assume that all other variables are held constant at their means.
